# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\"\xef\x02\n\x0e\x45xecuteRequest\x12\x16\n\x0escript_content\x18\x01 \x01(\t\x12\x13\n\x0bscript_type\x18\x02 \x01(\t\x12?\n\x0cinput_params\x18\x03 \x03(\x0b\x32).executor.ExecuteRequest.InputParamsEntry\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05\x12\x10\n\x08work_dir\x18\x05 \x01(\t\x12\x37\n\x08\x65nv_vars\x18\x06 \x03(\x0b\x32%.executor.ExecuteRequest.EnvVarsEntry\x12\x12\n\nclass_name\x18\x07 \x01(\t\x12\x13\n\x0bmethod_name\x18\x08 \x01(\t\x1a\x32\n\x10InputParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0c\x45nvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x85\x01\n\x0f\x45xecuteResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x05\x12\x15\n\rerror_message\x18\x06 \x01(\t\"\x14\n\x12HealthCheckRequest\"O\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x16\n\x0epython_version\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9c\x01\n\x0ePythonExecutor\x12>\n\x07\x45xecute\x12\x18.executor.ExecuteRequest\x1a\x19.executor.ExecuteResponse\x12J\n\x0bHealthCheck\x12\x1c.executor.HealthCheckRequest\x1a\x1d.executor.HealthCheckResponseB,\n(com.cqie.datafactory.executor.grpc.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.cqie.datafactory.executor.grpc.protoP\001'
  _globals['_EXECUTEREQUEST_INPUTPARAMSENTRY']._loaded_options = None
  _globals['_EXECUTEREQUEST_INPUTPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTEREQUEST_ENVVARSENTRY']._loaded_options = None
  _globals['_EXECUTEREQUEST_ENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTEREQUEST']._serialized_start=29
  _globals['_EXECUTEREQUEST']._serialized_end=396
  _globals['_EXECUTEREQUEST_INPUTPARAMSENTRY']._serialized_start=298
  _globals['_EXECUTEREQUEST_INPUTPARAMSENTRY']._serialized_end=348
  _globals['_EXECUTEREQUEST_ENVVARSENTRY']._serialized_start=350
  _globals['_EXECUTEREQUEST_ENVVARSENTRY']._serialized_end=396
  _globals['_EXECUTERESPONSE']._serialized_start=399
  _globals['_EXECUTERESPONSE']._serialized_end=532
  _globals['_HEALTHCHECKREQUEST']._serialized_start=534
  _globals['_HEALTHCHECKREQUEST']._serialized_end=554
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=556
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=635
  _globals['_PYTHONEXECUTOR']._serialized_start=638
  _globals['_PYTHONEXECUTOR']._serialized_end=794
# @@protoc_insertion_point(module_scope)
