// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:executor.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 exit_code = 1;</code>
   * @return The exitCode.
   */
  int getExitCode();

  /**
   * <code>string stdout = 2;</code>
   * @return The stdout.
   */
  java.lang.String getStdout();
  /**
   * <code>string stdout = 2;</code>
   * @return The bytes for stdout.
   */
  com.google.protobuf.ByteString
      getStdoutBytes();

  /**
   * <code>string stderr = 3;</code>
   * @return The stderr.
   */
  java.lang.String getStderr();
  /**
   * <code>string stderr = 3;</code>
   * @return The bytes for stderr.
   */
  com.google.protobuf.ByteString
      getStderrBytes();

  /**
   * <code>string result_json = 4;</code>
   * @return The resultJson.
   */
  java.lang.String getResultJson();
  /**
   * <code>string result_json = 4;</code>
   * @return The bytes for resultJson.
   */
  com.google.protobuf.ByteString
      getResultJsonBytes();

  /**
   * <code>int32 duration_ms = 5;</code>
   * @return The durationMs.
   */
  int getDurationMs();

  /**
   * <code>string error_message = 6;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 6;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
