// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:executor.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string script_content = 1;</code>
   * @return The scriptContent.
   */
  java.lang.String getScriptContent();
  /**
   * <code>string script_content = 1;</code>
   * @return The bytes for scriptContent.
   */
  com.google.protobuf.ByteString
      getScriptContentBytes();

  /**
   * <code>string script_type = 2;</code>
   * @return The scriptType.
   */
  java.lang.String getScriptType();
  /**
   * <code>string script_type = 2;</code>
   * @return The bytes for scriptType.
   */
  com.google.protobuf.ByteString
      getScriptTypeBytes();

  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  int getInputParamsCount();
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  boolean containsInputParams(
      java.lang.String key);
  /**
   * Use {@link #getInputParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getInputParams();
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getInputParamsMap();
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  /* nullable */
java.lang.String getInputParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  java.lang.String getInputParamsOrThrow(
      java.lang.String key);

  /**
   * <code>int32 timeout_seconds = 4;</code>
   * @return The timeoutSeconds.
   */
  int getTimeoutSeconds();

  /**
   * <code>string work_dir = 5;</code>
   * @return The workDir.
   */
  java.lang.String getWorkDir();
  /**
   * <code>string work_dir = 5;</code>
   * @return The bytes for workDir.
   */
  com.google.protobuf.ByteString
      getWorkDirBytes();

  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  int getEnvVarsCount();
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  boolean containsEnvVars(
      java.lang.String key);
  /**
   * Use {@link #getEnvVarsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEnvVars();
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEnvVarsMap();
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  /* nullable */
java.lang.String getEnvVarsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  java.lang.String getEnvVarsOrThrow(
      java.lang.String key);

  /**
   * <code>string class_name = 7;</code>
   * @return The className.
   */
  java.lang.String getClassName();
  /**
   * <code>string class_name = 7;</code>
   * @return The bytes for className.
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>string method_name = 8;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string method_name = 8;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();
}
