// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

/**
 * Protobuf type {@code executor.ExecuteRequest}
 */
public final class ExecuteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:executor.ExecuteRequest)
    ExecuteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteRequest.newBuilder() to construct.
  private ExecuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteRequest() {
    scriptContent_ = "";
    scriptType_ = "";
    workDir_ = "";
    className_ = "";
    methodName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetInputParams();
      case 6:
        return internalGetEnvVars();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.class, com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.Builder.class);
  }

  public static final int SCRIPT_CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scriptContent_ = "";
  /**
   * <code>string script_content = 1;</code>
   * @return The scriptContent.
   */
  @java.lang.Override
  public java.lang.String getScriptContent() {
    java.lang.Object ref = scriptContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scriptContent_ = s;
      return s;
    }
  }
  /**
   * <code>string script_content = 1;</code>
   * @return The bytes for scriptContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScriptContentBytes() {
    java.lang.Object ref = scriptContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scriptContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCRIPT_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scriptType_ = "";
  /**
   * <code>string script_type = 2;</code>
   * @return The scriptType.
   */
  @java.lang.Override
  public java.lang.String getScriptType() {
    java.lang.Object ref = scriptType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scriptType_ = s;
      return s;
    }
  }
  /**
   * <code>string script_type = 2;</code>
   * @return The bytes for scriptType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScriptTypeBytes() {
    java.lang.Object ref = scriptType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scriptType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_PARAMS_FIELD_NUMBER = 3;
  private static final class InputParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_InputParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> inputParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetInputParams() {
    if (inputParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          InputParamsDefaultEntryHolder.defaultEntry);
    }
    return inputParams_;
  }
  public int getInputParamsCount() {
    return internalGetInputParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  @java.lang.Override
  public boolean containsInputParams(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetInputParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getInputParamsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getInputParams() {
    return getInputParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getInputParamsMap() {
    return internalGetInputParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getInputParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; input_params = 3;</code>
   */
  @java.lang.Override
  public java.lang.String getInputParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetInputParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIMEOUT_SECONDS_FIELD_NUMBER = 4;
  private int timeoutSeconds_ = 0;
  /**
   * <code>int32 timeout_seconds = 4;</code>
   * @return The timeoutSeconds.
   */
  @java.lang.Override
  public int getTimeoutSeconds() {
    return timeoutSeconds_;
  }

  public static final int WORK_DIR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object workDir_ = "";
  /**
   * <code>string work_dir = 5;</code>
   * @return The workDir.
   */
  @java.lang.Override
  public java.lang.String getWorkDir() {
    java.lang.Object ref = workDir_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workDir_ = s;
      return s;
    }
  }
  /**
   * <code>string work_dir = 5;</code>
   * @return The bytes for workDir.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkDirBytes() {
    java.lang.Object ref = workDir_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workDir_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENV_VARS_FIELD_NUMBER = 6;
  private static final class EnvVarsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_EnvVarsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> envVars_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetEnvVars() {
    if (envVars_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          EnvVarsDefaultEntryHolder.defaultEntry);
    }
    return envVars_;
  }
  public int getEnvVarsCount() {
    return internalGetEnvVars().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  @java.lang.Override
  public boolean containsEnvVars(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetEnvVars().getMap().containsKey(key);
  }
  /**
   * Use {@link #getEnvVarsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getEnvVars() {
    return getEnvVarsMap();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getEnvVarsMap() {
    return internalGetEnvVars().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getEnvVarsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnvVars().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; env_vars = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getEnvVarsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetEnvVars().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CLASS_NAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object className_ = "";
  /**
   * <code>string class_name = 7;</code>
   * @return The className.
   */
  @java.lang.Override
  public java.lang.String getClassName() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      className_ = s;
      return s;
    }
  }
  /**
   * <code>string class_name = 7;</code>
   * @return The bytes for className.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClassNameBytes() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      className_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_NAME_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object methodName_ = "";
  /**
   * <code>string method_name = 8;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public java.lang.String getMethodName() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodName_ = s;
      return s;
    }
  }
  /**
   * <code>string method_name = 8;</code>
   * @return The bytes for methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, scriptContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scriptType_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetInputParams(),
        InputParamsDefaultEntryHolder.defaultEntry,
        3);
    if (timeoutSeconds_ != 0) {
      output.writeInt32(4, timeoutSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workDir_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, workDir_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetEnvVars(),
        EnvVarsDefaultEntryHolder.defaultEntry,
        6);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, className_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, methodName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, scriptContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scriptType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scriptType_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetInputParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      inputParams__ = InputParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, inputParams__);
    }
    if (timeoutSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, timeoutSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workDir_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, workDir_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetEnvVars().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      envVars__ = EnvVarsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, envVars__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, className_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, methodName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cqie.datafactory.executor.grpc.proto.ExecuteRequest)) {
      return super.equals(obj);
    }
    com.cqie.datafactory.executor.grpc.proto.ExecuteRequest other = (com.cqie.datafactory.executor.grpc.proto.ExecuteRequest) obj;

    if (!getScriptContent()
        .equals(other.getScriptContent())) return false;
    if (!getScriptType()
        .equals(other.getScriptType())) return false;
    if (!internalGetInputParams().equals(
        other.internalGetInputParams())) return false;
    if (getTimeoutSeconds()
        != other.getTimeoutSeconds()) return false;
    if (!getWorkDir()
        .equals(other.getWorkDir())) return false;
    if (!internalGetEnvVars().equals(
        other.internalGetEnvVars())) return false;
    if (!getClassName()
        .equals(other.getClassName())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCRIPT_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getScriptContent().hashCode();
    hash = (37 * hash) + SCRIPT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getScriptType().hashCode();
    if (!internalGetInputParams().getMap().isEmpty()) {
      hash = (37 * hash) + INPUT_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetInputParams().hashCode();
    }
    hash = (37 * hash) + TIMEOUT_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeoutSeconds();
    hash = (37 * hash) + WORK_DIR_FIELD_NUMBER;
    hash = (53 * hash) + getWorkDir().hashCode();
    if (!internalGetEnvVars().getMap().isEmpty()) {
      hash = (37 * hash) + ENV_VARS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetEnvVars().hashCode();
    }
    hash = (37 * hash) + CLASS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClassName().hashCode();
    hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cqie.datafactory.executor.grpc.proto.ExecuteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code executor.ExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:executor.ExecuteRequest)
      com.cqie.datafactory.executor.grpc.proto.ExecuteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetInputParams();
        case 6:
          return internalGetEnvVars();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableInputParams();
        case 6:
          return internalGetMutableEnvVars();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.class, com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.Builder.class);
    }

    // Construct using com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scriptContent_ = "";
      scriptType_ = "";
      internalGetMutableInputParams().clear();
      timeoutSeconds_ = 0;
      workDir_ = "";
      internalGetMutableEnvVars().clear();
      className_ = "";
      methodName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteRequest_descriptor;
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteRequest getDefaultInstanceForType() {
      return com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteRequest build() {
      com.cqie.datafactory.executor.grpc.proto.ExecuteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteRequest buildPartial() {
      com.cqie.datafactory.executor.grpc.proto.ExecuteRequest result = new com.cqie.datafactory.executor.grpc.proto.ExecuteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cqie.datafactory.executor.grpc.proto.ExecuteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scriptContent_ = scriptContent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.scriptType_ = scriptType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.inputParams_ = internalGetInputParams();
        result.inputParams_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timeoutSeconds_ = timeoutSeconds_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.workDir_ = workDir_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.envVars_ = internalGetEnvVars();
        result.envVars_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.className_ = className_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.methodName_ = methodName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cqie.datafactory.executor.grpc.proto.ExecuteRequest) {
        return mergeFrom((com.cqie.datafactory.executor.grpc.proto.ExecuteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cqie.datafactory.executor.grpc.proto.ExecuteRequest other) {
      if (other == com.cqie.datafactory.executor.grpc.proto.ExecuteRequest.getDefaultInstance()) return this;
      if (!other.getScriptContent().isEmpty()) {
        scriptContent_ = other.scriptContent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getScriptType().isEmpty()) {
        scriptType_ = other.scriptType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      internalGetMutableInputParams().mergeFrom(
          other.internalGetInputParams());
      bitField0_ |= 0x00000004;
      if (other.getTimeoutSeconds() != 0) {
        setTimeoutSeconds(other.getTimeoutSeconds());
      }
      if (!other.getWorkDir().isEmpty()) {
        workDir_ = other.workDir_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      internalGetMutableEnvVars().mergeFrom(
          other.internalGetEnvVars());
      bitField0_ |= 0x00000020;
      if (!other.getClassName().isEmpty()) {
        className_ = other.className_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getMethodName().isEmpty()) {
        methodName_ = other.methodName_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              scriptContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              scriptType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              inputParams__ = input.readMessage(
                  InputParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableInputParams().getMutableMap().put(
                  inputParams__.getKey(), inputParams__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              timeoutSeconds_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              workDir_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              envVars__ = input.readMessage(
                  EnvVarsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableEnvVars().getMutableMap().put(
                  envVars__.getKey(), envVars__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              className_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              methodName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object scriptContent_ = "";
    /**
     * <code>string script_content = 1;</code>
     * @return The scriptContent.
     */
    public java.lang.String getScriptContent() {
      java.lang.Object ref = scriptContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scriptContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string script_content = 1;</code>
     * @return The bytes for scriptContent.
     */
    public com.google.protobuf.ByteString
        getScriptContentBytes() {
      java.lang.Object ref = scriptContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scriptContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string script_content = 1;</code>
     * @param value The scriptContent to set.
     * @return This builder for chaining.
     */
    public Builder setScriptContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scriptContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string script_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScriptContent() {
      scriptContent_ = getDefaultInstance().getScriptContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string script_content = 1;</code>
     * @param value The bytes for scriptContent to set.
     * @return This builder for chaining.
     */
    public Builder setScriptContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scriptContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object scriptType_ = "";
    /**
     * <code>string script_type = 2;</code>
     * @return The scriptType.
     */
    public java.lang.String getScriptType() {
      java.lang.Object ref = scriptType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scriptType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string script_type = 2;</code>
     * @return The bytes for scriptType.
     */
    public com.google.protobuf.ByteString
        getScriptTypeBytes() {
      java.lang.Object ref = scriptType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scriptType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string script_type = 2;</code>
     * @param value The scriptType to set.
     * @return This builder for chaining.
     */
    public Builder setScriptType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scriptType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string script_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScriptType() {
      scriptType_ = getDefaultInstance().getScriptType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string script_type = 2;</code>
     * @param value The bytes for scriptType to set.
     * @return This builder for chaining.
     */
    public Builder setScriptTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scriptType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> inputParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetInputParams() {
      if (inputParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputParamsDefaultEntryHolder.defaultEntry);
      }
      return inputParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableInputParams() {
      if (inputParams_ == null) {
        inputParams_ = com.google.protobuf.MapField.newMapField(
            InputParamsDefaultEntryHolder.defaultEntry);
      }
      if (!inputParams_.isMutable()) {
        inputParams_ = inputParams_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return inputParams_;
    }
    public int getInputParamsCount() {
      return internalGetInputParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    @java.lang.Override
    public boolean containsInputParams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetInputParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputParamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getInputParams() {
      return getInputParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getInputParamsMap() {
      return internalGetInputParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getInputParamsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getInputParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetInputParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearInputParams() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableInputParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    public Builder removeInputParams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableInputParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableInputParams() {
      bitField0_ |= 0x00000004;
      return internalGetMutableInputParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    public Builder putInputParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableInputParams().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; input_params = 3;</code>
     */
    public Builder putAllInputParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableInputParams().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private int timeoutSeconds_ ;
    /**
     * <code>int32 timeout_seconds = 4;</code>
     * @return The timeoutSeconds.
     */
    @java.lang.Override
    public int getTimeoutSeconds() {
      return timeoutSeconds_;
    }
    /**
     * <code>int32 timeout_seconds = 4;</code>
     * @param value The timeoutSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutSeconds(int value) {

      timeoutSeconds_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeout_seconds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutSeconds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timeoutSeconds_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object workDir_ = "";
    /**
     * <code>string work_dir = 5;</code>
     * @return The workDir.
     */
    public java.lang.String getWorkDir() {
      java.lang.Object ref = workDir_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workDir_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string work_dir = 5;</code>
     * @return The bytes for workDir.
     */
    public com.google.protobuf.ByteString
        getWorkDirBytes() {
      java.lang.Object ref = workDir_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string work_dir = 5;</code>
     * @param value The workDir to set.
     * @return This builder for chaining.
     */
    public Builder setWorkDir(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      workDir_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string work_dir = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkDir() {
      workDir_ = getDefaultInstance().getWorkDir();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string work_dir = 5;</code>
     * @param value The bytes for workDir to set.
     * @return This builder for chaining.
     */
    public Builder setWorkDirBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      workDir_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> envVars_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetEnvVars() {
      if (envVars_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EnvVarsDefaultEntryHolder.defaultEntry);
      }
      return envVars_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableEnvVars() {
      if (envVars_ == null) {
        envVars_ = com.google.protobuf.MapField.newMapField(
            EnvVarsDefaultEntryHolder.defaultEntry);
      }
      if (!envVars_.isMutable()) {
        envVars_ = envVars_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return envVars_;
    }
    public int getEnvVarsCount() {
      return internalGetEnvVars().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    @java.lang.Override
    public boolean containsEnvVars(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetEnvVars().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEnvVarsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getEnvVars() {
      return getEnvVarsMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getEnvVarsMap() {
      return internalGetEnvVars().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getEnvVarsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnvVars().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getEnvVarsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetEnvVars().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearEnvVars() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableEnvVars().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    public Builder removeEnvVars(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableEnvVars().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableEnvVars() {
      bitField0_ |= 0x00000020;
      return internalGetMutableEnvVars().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    public Builder putEnvVars(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableEnvVars().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; env_vars = 6;</code>
     */
    public Builder putAllEnvVars(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableEnvVars().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private java.lang.Object className_ = "";
    /**
     * <code>string class_name = 7;</code>
     * @return The className.
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string class_name = 7;</code>
     * @return The bytes for className.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string class_name = 7;</code>
     * @param value The className to set.
     * @return This builder for chaining.
     */
    public Builder setClassName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      className_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearClassName() {
      className_ = getDefaultInstance().getClassName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string class_name = 7;</code>
     * @param value The bytes for className to set.
     * @return This builder for chaining.
     */
    public Builder setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      className_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object methodName_ = "";
    /**
     * <code>string method_name = 8;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method_name = 8;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method_name = 8;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      methodName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string method_name = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      methodName_ = getDefaultInstance().getMethodName();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string method_name = 8;</code>
     * @param value The bytes for methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      methodName_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:executor.ExecuteRequest)
  }

  // @@protoc_insertion_point(class_scope:executor.ExecuteRequest)
  private static final com.cqie.datafactory.executor.grpc.proto.ExecuteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cqie.datafactory.executor.grpc.proto.ExecuteRequest();
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteRequest>() {
    @java.lang.Override
    public ExecuteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cqie.datafactory.executor.grpc.proto.ExecuteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

