// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

public final class Executor {
  private Executor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_ExecuteRequest_InputParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_ExecuteRequest_InputParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_ExecuteRequest_EnvVarsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_ExecuteRequest_EnvVarsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_executor_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_executor_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016executor.proto\022\010executor\"\357\002\n\016ExecuteRe" +
      "quest\022\026\n\016script_content\030\001 \001(\t\022\023\n\013script_" +
      "type\030\002 \001(\t\022?\n\014input_params\030\003 \003(\0132).execu" +
      "tor.ExecuteRequest.InputParamsEntry\022\027\n\017t" +
      "imeout_seconds\030\004 \001(\005\022\020\n\010work_dir\030\005 \001(\t\0227" +
      "\n\010env_vars\030\006 \003(\0132%.executor.ExecuteReque" +
      "st.EnvVarsEntry\022\022\n\nclass_name\030\007 \001(\t\022\023\n\013m" +
      "ethod_name\030\010 \001(\t\0322\n\020InputParamsEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032.\n\014EnvVarsE" +
      "ntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\205\001\n" +
      "\017ExecuteResponse\022\021\n\texit_code\030\001 \001(\005\022\016\n\006s" +
      "tdout\030\002 \001(\t\022\016\n\006stderr\030\003 \001(\t\022\023\n\013result_js" +
      "on\030\004 \001(\t\022\023\n\013duration_ms\030\005 \001(\005\022\025\n\rerror_m" +
      "essage\030\006 \001(\t\"\024\n\022HealthCheckRequest\"O\n\023He" +
      "althCheckResponse\022\017\n\007healthy\030\001 \001(\010\022\026\n\016py" +
      "thon_version\030\002 \001(\t\022\017\n\007message\030\003 \001(\t2\234\001\n\016" +
      "PythonExecutor\022>\n\007Execute\022\030.executor.Exe" +
      "cuteRequest\032\031.executor.ExecuteResponse\022J" +
      "\n\013HealthCheck\022\034.executor.HealthCheckRequ" +
      "est\032\035.executor.HealthCheckResponseB,\n(co" +
      "m.cqie.datafactory.executor.grpc.protoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_executor_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_executor_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_ExecuteRequest_descriptor,
        new java.lang.String[] { "ScriptContent", "ScriptType", "InputParams", "TimeoutSeconds", "WorkDir", "EnvVars", "ClassName", "MethodName", });
    internal_static_executor_ExecuteRequest_InputParamsEntry_descriptor =
      internal_static_executor_ExecuteRequest_descriptor.getNestedTypes().get(0);
    internal_static_executor_ExecuteRequest_InputParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_ExecuteRequest_InputParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_executor_ExecuteRequest_EnvVarsEntry_descriptor =
      internal_static_executor_ExecuteRequest_descriptor.getNestedTypes().get(1);
    internal_static_executor_ExecuteRequest_EnvVarsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_ExecuteRequest_EnvVarsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_executor_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_executor_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_ExecuteResponse_descriptor,
        new java.lang.String[] { "ExitCode", "Stdout", "Stderr", "ResultJson", "DurationMs", "ErrorMessage", });
    internal_static_executor_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_executor_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_executor_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_executor_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_executor_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Healthy", "PythonVersion", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
