// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

/**
 * Protobuf type {@code executor.ExecuteResponse}
 */
public final class ExecuteResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:executor.ExecuteResponse)
    ExecuteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteResponse.newBuilder() to construct.
  private ExecuteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteResponse() {
    stdout_ = "";
    stderr_ = "";
    resultJson_ = "";
    errorMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.class, com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.Builder.class);
  }

  public static final int EXIT_CODE_FIELD_NUMBER = 1;
  private int exitCode_ = 0;
  /**
   * <code>int32 exit_code = 1;</code>
   * @return The exitCode.
   */
  @java.lang.Override
  public int getExitCode() {
    return exitCode_;
  }

  public static final int STDOUT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stdout_ = "";
  /**
   * <code>string stdout = 2;</code>
   * @return The stdout.
   */
  @java.lang.Override
  public java.lang.String getStdout() {
    java.lang.Object ref = stdout_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stdout_ = s;
      return s;
    }
  }
  /**
   * <code>string stdout = 2;</code>
   * @return The bytes for stdout.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStdoutBytes() {
    java.lang.Object ref = stdout_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stdout_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STDERR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stderr_ = "";
  /**
   * <code>string stderr = 3;</code>
   * @return The stderr.
   */
  @java.lang.Override
  public java.lang.String getStderr() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stderr_ = s;
      return s;
    }
  }
  /**
   * <code>string stderr = 3;</code>
   * @return The bytes for stderr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStderrBytes() {
    java.lang.Object ref = stderr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stderr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULT_JSON_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resultJson_ = "";
  /**
   * <code>string result_json = 4;</code>
   * @return The resultJson.
   */
  @java.lang.Override
  public java.lang.String getResultJson() {
    java.lang.Object ref = resultJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultJson_ = s;
      return s;
    }
  }
  /**
   * <code>string result_json = 4;</code>
   * @return The bytes for resultJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultJsonBytes() {
    java.lang.Object ref = resultJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_MS_FIELD_NUMBER = 5;
  private int durationMs_ = 0;
  /**
   * <code>int32 duration_ms = 5;</code>
   * @return The durationMs.
   */
  @java.lang.Override
  public int getDurationMs() {
    return durationMs_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 6;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 6;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exitCode_ != 0) {
      output.writeInt32(1, exitCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stdout_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultJson_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, resultJson_);
    }
    if (durationMs_ != 0) {
      output.writeInt32(5, durationMs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exitCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, exitCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stdout_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stdout_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stderr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stderr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resultJson_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, resultJson_);
    }
    if (durationMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, durationMs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cqie.datafactory.executor.grpc.proto.ExecuteResponse)) {
      return super.equals(obj);
    }
    com.cqie.datafactory.executor.grpc.proto.ExecuteResponse other = (com.cqie.datafactory.executor.grpc.proto.ExecuteResponse) obj;

    if (getExitCode()
        != other.getExitCode()) return false;
    if (!getStdout()
        .equals(other.getStdout())) return false;
    if (!getStderr()
        .equals(other.getStderr())) return false;
    if (!getResultJson()
        .equals(other.getResultJson())) return false;
    if (getDurationMs()
        != other.getDurationMs()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXIT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getExitCode();
    hash = (37 * hash) + STDOUT_FIELD_NUMBER;
    hash = (53 * hash) + getStdout().hashCode();
    hash = (37 * hash) + STDERR_FIELD_NUMBER;
    hash = (53 * hash) + getStderr().hashCode();
    hash = (37 * hash) + RESULT_JSON_FIELD_NUMBER;
    hash = (53 * hash) + getResultJson().hashCode();
    hash = (37 * hash) + DURATION_MS_FIELD_NUMBER;
    hash = (53 * hash) + getDurationMs();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cqie.datafactory.executor.grpc.proto.ExecuteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code executor.ExecuteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:executor.ExecuteResponse)
      com.cqie.datafactory.executor.grpc.proto.ExecuteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.class, com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.Builder.class);
    }

    // Construct using com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      exitCode_ = 0;
      stdout_ = "";
      stderr_ = "";
      resultJson_ = "";
      durationMs_ = 0;
      errorMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cqie.datafactory.executor.grpc.proto.Executor.internal_static_executor_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteResponse getDefaultInstanceForType() {
      return com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteResponse build() {
      com.cqie.datafactory.executor.grpc.proto.ExecuteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cqie.datafactory.executor.grpc.proto.ExecuteResponse buildPartial() {
      com.cqie.datafactory.executor.grpc.proto.ExecuteResponse result = new com.cqie.datafactory.executor.grpc.proto.ExecuteResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cqie.datafactory.executor.grpc.proto.ExecuteResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.exitCode_ = exitCode_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stdout_ = stdout_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stderr_ = stderr_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resultJson_ = resultJson_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.durationMs_ = durationMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cqie.datafactory.executor.grpc.proto.ExecuteResponse) {
        return mergeFrom((com.cqie.datafactory.executor.grpc.proto.ExecuteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cqie.datafactory.executor.grpc.proto.ExecuteResponse other) {
      if (other == com.cqie.datafactory.executor.grpc.proto.ExecuteResponse.getDefaultInstance()) return this;
      if (other.getExitCode() != 0) {
        setExitCode(other.getExitCode());
      }
      if (!other.getStdout().isEmpty()) {
        stdout_ = other.stdout_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getStderr().isEmpty()) {
        stderr_ = other.stderr_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getResultJson().isEmpty()) {
        resultJson_ = other.resultJson_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getDurationMs() != 0) {
        setDurationMs(other.getDurationMs());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              exitCode_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              stdout_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              stderr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              resultJson_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              durationMs_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int exitCode_ ;
    /**
     * <code>int32 exit_code = 1;</code>
     * @return The exitCode.
     */
    @java.lang.Override
    public int getExitCode() {
      return exitCode_;
    }
    /**
     * <code>int32 exit_code = 1;</code>
     * @param value The exitCode to set.
     * @return This builder for chaining.
     */
    public Builder setExitCode(int value) {

      exitCode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 exit_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExitCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      exitCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object stdout_ = "";
    /**
     * <code>string stdout = 2;</code>
     * @return The stdout.
     */
    public java.lang.String getStdout() {
      java.lang.Object ref = stdout_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stdout_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @return The bytes for stdout.
     */
    public com.google.protobuf.ByteString
        getStdoutBytes() {
      java.lang.Object ref = stdout_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stdout_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdout(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stdout_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStdout() {
      stdout_ = getDefaultInstance().getStdout();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string stdout = 2;</code>
     * @param value The bytes for stdout to set.
     * @return This builder for chaining.
     */
    public Builder setStdoutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stdout_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object stderr_ = "";
    /**
     * <code>string stderr = 3;</code>
     * @return The stderr.
     */
    public java.lang.String getStderr() {
      java.lang.Object ref = stderr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stderr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stderr = 3;</code>
     * @return The bytes for stderr.
     */
    public com.google.protobuf.ByteString
        getStderrBytes() {
      java.lang.Object ref = stderr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stderr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stderr = 3;</code>
     * @param value The stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stderr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStderr() {
      stderr_ = getDefaultInstance().getStderr();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string stderr = 3;</code>
     * @param value The bytes for stderr to set.
     * @return This builder for chaining.
     */
    public Builder setStderrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stderr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object resultJson_ = "";
    /**
     * <code>string result_json = 4;</code>
     * @return The resultJson.
     */
    public java.lang.String getResultJson() {
      java.lang.Object ref = resultJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result_json = 4;</code>
     * @return The bytes for resultJson.
     */
    public com.google.protobuf.ByteString
        getResultJsonBytes() {
      java.lang.Object ref = resultJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result_json = 4;</code>
     * @param value The resultJson to set.
     * @return This builder for chaining.
     */
    public Builder setResultJson(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resultJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string result_json = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultJson() {
      resultJson_ = getDefaultInstance().getResultJson();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string result_json = 4;</code>
     * @param value The bytes for resultJson to set.
     * @return This builder for chaining.
     */
    public Builder setResultJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resultJson_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int durationMs_ ;
    /**
     * <code>int32 duration_ms = 5;</code>
     * @return The durationMs.
     */
    @java.lang.Override
    public int getDurationMs() {
      return durationMs_;
    }
    /**
     * <code>int32 duration_ms = 5;</code>
     * @param value The durationMs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMs(int value) {

      durationMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 duration_ms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      durationMs_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 6;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 6;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 6;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 6;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:executor.ExecuteResponse)
  }

  // @@protoc_insertion_point(class_scope:executor.ExecuteResponse)
  private static final com.cqie.datafactory.executor.grpc.proto.ExecuteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cqie.datafactory.executor.grpc.proto.ExecuteResponse();
  }

  public static com.cqie.datafactory.executor.grpc.proto.ExecuteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteResponse>() {
    @java.lang.Override
    public ExecuteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cqie.datafactory.executor.grpc.proto.ExecuteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

