// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:executor.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {
}
