// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: executor.proto

// Protobuf Java Version: 3.25.5
package com.cqie.datafactory.executor.grpc.proto;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:executor.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool healthy = 1;</code>
   * @return The healthy.
   */
  boolean getHealthy();

  /**
   * <code>string python_version = 2;</code>
   * @return The pythonVersion.
   */
  java.lang.String getPythonVersion();
  /**
   * <code>string python_version = 2;</code>
   * @return The bytes for pythonVersion.
   */
  com.google.protobuf.ByteString
      getPythonVersionBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
