global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'datafactory-configuration'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'datafactory-executor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
